config/routes.rb
Rails.application.routes.draw do

  get "/events", to: "events#index"

  resources :events
  resources :tracking_plans
  namespace :api do
    namespace :v1 do
      resources :events
      resources :tracking_plans
      post 'tracking_plans/add_events/:id' => 'tracking_plans#add_events'
      get 'tracking_plans/get_events/:id' => 'tracking_plans#get_events'
      post 'send_event' => 'send_event_api#send_event'
    end
    # post '/events/create_event' => 'events_api#create_event'
  end
end

app/models/tracking_plan.rb
class TrackingPlan < ApplicationRecord
  has_many :tracking_plan_to_event_mappings, dependent: :destroy
  has_many :events, through: :tracking_plan_to_event_mappings
  accepts_nested_attributes_for :tracking_plan_to_event_mappings, allow_destroy: true
  accepts_nested_attributes_for :events, allow_destroy: true

  def self.create_plan(params)
    name = params[:name]
    description = params[:description]
    rules = params[:rules]
    events = params[:events]

    return [false, 'Missing params', nil] if name.blank?

    event_ids = []
    if events.present?
      events = TrackingPlan.sanitize_events(events)
      rules=  {}
      rules[:events] = events
    end
    if rules.present?
      success, error_message, event_ids = TrackingPlan.validate_rules(rules)
      return [false, error_message, nil] if !success
    end
    tracking_plan = TrackingPlan.create(name: name, description: description)
    unless event_ids.blank?
      event_ids.each do |event_id|
        TrackingPlanToEventMapping.create(tracking_plan_id: tracking_plan.id, event_id: event_id)
      end
    end
    [true, 'Successfully created Tracking plan!', tracking_plan]
  end

  def self.update_plan(params)
    id = params[:id]
    tracking_plan = TrackingPlan.find_by(id: id)
    return [false, 'Tracking Plan not found', nil] if tracking_plan.blank?
    events = params[:events]
    event_ids = []
    rules=  {}
    if events.present?
      events = TrackingPlan.sanitize_events(events)
      rules[:events] = events
    end
    if rules.present?
      success, error_message, event_ids = TrackingPlan.validate_rules(rules, true, tracking_plan.id)
      return [false, error_message, nil] if !success
    end
    tracking_plan.name = params[:name] if params[:name].present?
    tracking_plan.description = params[:description] if params[:description].present?
    tracking_plan = tracking_plan.save
    unless event_ids.blank?
      event_ids.each do |event_id|
        TrackingPlanToEventMapping.create(tracking_plan_id: id, event_id: event_id)
      end
    end
    [true, 'Updated tracking plan!', tracking_plan]
  end

  def self.add_events

  end

  def self.remove_events

  end

  def self.validate_rules(rules, is_update=false, tracking_plan_id = nil)
    return [false, 'Event Parameters missing', nil] if rules.blank?
    event_ids = []
    unless rules[:events].blank?
      event_names = []
      events = rules[:events]
      events.each do |event|
        return [false, 'Event Parameters missing', event_ids] if event[:name].blank? || event[:rules].blank?
        event_names << event[:name]
      end
      if Event.where(name: event_names).exists?
        unless is_update
          return [false, 'Event name already exists', event_ids]
        end
      end

      events.each do |event|
        if is_update
          old_event = Event.find_by(name: event[:name])
          if old_event.present?
            if !event[:remove]
              next
            elsif is_update && event[:remove]
              event_id = Event.find_by(name: event[:name]).id
              TrackingPlanToEventMapping.where(event_id: event_id, tracking_plan_id: tracking_plan_id).last&.destroy
              next
            end
          end
        end
        event = Event.create(name: event[:name], description:  event[:description], rules:  event[:rules])
        event_ids << event.id
      end
      return [true, 'Events created', event_ids]
    end
    return [false, 'No events passed', event_ids]
  end

  def self.sanitize_events(events)
    sanitized_events = []
    events.each do |event|
        sanitized_events << {
          name: event["name"],
          description: event["description"],
          rules: event["rules"],
          remove: event["_destroy"] == "1"
        }
    end
    sanitized_events
  end

end

app/controllers/api/v1/tracking_plans_controller.rb
module Api
  module V1
    class TrackingPlansController < ApiController
      def create
        success, error_message, tracking_plan = TrackingPlan.create_plan(params)
        unless success
          return response_data({}, error_message, 422, error: {})
        end
        response_data({tracking_plan: tracking_plan.as_json} , message, 200, error: {})
      end

      def index
        response_data(TrackingPlan.all.as_json, 'All plans!', 200, error: {})
      end

      def update
        success, message, tracking_plan = TrackingPlan.update_plan(params)
        unless success
          return response_data({}, message, 422, error: {})
        end

        response_data(tracking_plan.as_json, message, 200, error: {})
      end

      def add_events
        id = params[:id]
        event_names = params[:event_names]
        tracking_plan = TrackingPlan.find_by(id: id)
        return response_data({}, 'Event names not present', 422, error: {}) if event_names.blank?
        return response_data({}, 'Tracking Plan not found', 422, error: {}) if tracking_plan.blank?

        events = Event.where(name: event_names)
        if events.size != event_names.size
          return response_data({}, 'Not all valid event names', 422, error: {})
        end
        event_ids = events.pluck(:id)
        if TrackingPlanToEventMapping.where(event_id: event_ids, tracking_plan_id: id).exists?
          return response_data({}, 'Some associations already exist', 422, error: {})
        end
        event_ids.each do |event_id|
          TrackingPlanToEventMapping.create(event_id: event_id, tracking_plan_id: id)
        end
        response_data(TrackingPlan.find_by(id: id).as_json, 'Successfully added associations',
                      200, error: {})
      end

      def remove_events
        id = params[:id]
        event_names = params[:event_names]
        tracking_plan = TrackingPlan.find_by(id: id)
        return response_data({}, 'Event names not present', 422, error: {}) if event_names.blank?
        return response_data({}, 'Tracking Plan not found', 422, error: {}) if tracking_plan.blank?

        events = Event.where(name: event_names)
        if events.size != event_names.size
          return response_data({}, 'Not all valid event names', 422, error: {})
        end
        event_ids = events.pluck(:id)
        tp_event_mappings = TrackingPlanToEventMapping.where(event_id: event_ids, tracking_plan_id: id)
        if tp_event_mappings.size != event_names.size
          return response_data({}, 'Some associations dont exist', 422, error: {})
        end
        tp_event_mappings.destroy_all

        response_data(TrackingPlan.find_by(id: id).as_json, 'Successfully added associations',
                      200, error: {})
      end

      def get_events
        id = params[:id]
        tracking_plan = TrackingPlan.find_by(id: id)
        return response_data({}, 'Tracking Plan not found', 422, error: {}) if tracking_plan.blank?
        event_ids = TrackingPlanToEventMapping.where(tracking_plan_id: id).pluck(:event_id)
        events = Event.where(id: event_ids)
        response_data(events.as_json, 'Events for the tracking plan',
                      200, error: {})
      end

      private

      def validate_rules(rules)
        event_ids = []
        unless rules[:events].blank?
          event_names = []
          events = rules[:events]
          events.each do |event|
            return [false, 'Event Parameters missing', event_ids] if event[:name].blank? || event[:rules].blank?
            event_names << event[:name]
          end
          return [false, 'Event name already exists', event_ids] if Event.where(name: event_names).exists?

          events.each do |event|
            event = Event.create(name: event[:name], description:  event[:description], rules:  event[:rules])
            event_ids << event.id
          end
        return [true, 'Events created', event_ids]
        end
        return [false, 'No events passed', event_ids]
      end
    end
  end
end

app/controllers/tracking_plans_controller.rb
class TrackingPlansController < ApplicationController
  before_action :set_tracking_plan, only: [:show, :edit, :update]
  before_action :set_events, only: [:edit, :update, :new, :create]
  def index
    @tracking_plans = TrackingPlan.all
  end

  def new
    @tracking_plan = TrackingPlan.new
  end

  def edit; end

  def create
    @tracking_plan = TrackingPlan.new(tracking_plan_params)
    tracking_plan = params["tracking_plan"]
    name = tracking_plan["name"]
    description = tracking_plan["description"]
    events  = tracking_plan["events_attributes"]&.values

    respond_to do |format|
      if params[:add_event]
        @tracking_plan.events.build
        format.html { render :new, status: :unprocessable_entity }
      else

        success, message, @tracking_plan = TrackingPlan.create_plan(
          {name: name, description: description, events: events})
        if success
          # @tracking_plan = event
          format.html { redirect_to tracking_plans_path, notice: 'Event successfully updated.' }
          format.json { render :show, status: :created, location: @tracking_plan }
        else
          format.html { render :new }
          format.json { render json: message, status: :unprocessable_entity }
        end
      end
    end
  end

  def update
    tracking_plan = params["tracking_plan"]
    name = tracking_plan["name"]
    events  = tracking_plan["events_attributes"]&.values
    description = tracking_plan["description"]
    respond_to do |format|
      if params[:add_event]
        @tracking_plan.events.build
        format.html { render :new, status: :unprocessable_entity }
      else
        success, message, @tracking_plan = TrackingPlan.update_plan(
          {name: name, description: description, events: events, id: params["id"]})

        if success
          # @tracking_plan = event
          format.html { redirect_to tracking_plans_path, notice: 'plan successfully updated.' }
          format.json { render :show, status: :created, location: @tracking_plan }
        else
          format.html { render :edit }
          format.json { render json: message, status: :unprocessable_entity }
        end
      end
    end
  end



  private

  def set_tracking_plan
    @tracking_plan = TrackingPlan.find(params[:id])
  end

  def tracking_plan_params
    params.require(:tracking_plan).permit(
      :name, :description, :rules,
      # tracking_plan_to_event_mappings_attributes:
      #   [:id, :_destroy, :tracking_plan_id, :event_id],
      events_attributes: [:id, :name, :description, :rules, :_destroy])
  end

  private

  def set_events
    @events = Event.all.order(id: :desc).pluck(:name, :id)
  end
end

app/helpers/api/v1/tracking_plans_helper.rb
module Api::V1::TrackingPlansHelper
end

app/helpers/tracking_plans_helper.rb
module TrackingPlansHelper
end

app/views/tracking_plans/_event_fields.html.erb
<fieldset style="width: 600px">
  <%= f.label :name %><br>
  <div class="selectField">
    <%= f.text_field :name   %>
  </div>
  <div class="selectField">
    <%= f.text_field :description   %>
  </div>
  <div class="selectField">
    <%= f.text_field :rules   %>
  </div>


  <%= f.hidden_field :_destroy %>
  <%= link_to "Remove", '#', class: "remove_fields" %>
</fieldset>

app/views/tracking_plans/_form.html.erb
<div class="home-form-container" style="width: 90%; margin: auto;">
  <%= form_for @tracking_plan, :html => {id: 'event_form', class: 'page-content'} do |f| %>
    <!--   Checking for error-->
    <% if @tracking_plan.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@tracking_plan.errors.count, "error") %> prohibited this page from being saved:</h2>
        <ul>
          <% @tracking_plan.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="form-group">
      <%= f.label :name %><br>
      <%= f.text_field :name, class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= f.label :description %><br>
      <%= f.text_field :description, class: 'form-control' %>
    </div>

    <%= f.fields_for :events do |ff| %>
      <div class="flex gap-2" style="width: 100%;background: lightblue;padding: 20px;margin-bottom: 10px">
        <%= ff.label :remove_event, style: "margin-top:-2px;" %>
        <%= ff.check_box :_destroy, title: "Remove Event", style: "margin-left:10px;margin-top:2px;" %>

        <div class="selectField" style="margin-top: 15px">
          <%= ff.label :name %><br>

          <%= ff.text_field :name   %>
        </div>
        <div class="selectField" style="margin-top: 15px">
          <%= ff.label :description %><br>
          <%= ff.text_field :description   %>
        </div>
        <div class="selectField" style="margin-top: 15px">
          <%= ff.label :rules %><br>
          <%= ff.text_area :rules, class: "form-textarea-input", cols: 100, rows: 10   %>
        </div>

      </div>
    <% end %>

    <%= f.submit "Add Event", name: :add_event %>

  <% end %>
</div>

<script type="text/javascript">
    function submitForm() {
        const form = document.getElementById('event_form');
        form.submit();
    }

</script>

app/views/tracking_plans/edit.html.erb
<div class="page-layout simple tabbed">

  <!-- HEADER -->
  <div class="page-header bg-primary text-auto row no-gutters align-items-center justify-content-between p-6">
    <div class="row no-gutters align-items-center" style="margin-left: 30px;padding: 10px;">
      <div style="font-size: 32px;font-weight: 700;">Edit Tracking Plan</div>
    </div>

    <button type="button" class="btn btn-light" onclick="submitForm()" style="margin-left:40px;">
      SAVE
    </button>

  </div>
  <!-- / HEADER -->

  <!-- CONTENT -->
  <%= render 'form', form_type: 'edit' %>
  <!-- / CONTENT -->
</div>

app/views/tracking_plans/index.html.erb
<div style="margin:10px 10px; font-size: 48px; font-width: 700;">
  Tracking Plans
</div>

<table class="table dataTable">

  <thead>
  <tr>
    <th>
      <div class="table-header">
        <span class="column-title">ID</span>
      </div>
    </th>

    <th>
      <div class="table-header">
        <span class="column-title">Name</span>
      </div>
    </th>


    <th>
      <div class="table-header">
        <span class="column-title">Actions</span>
      </div>
    </th>
  </tr>
  </thead>

  <tbody >
  <% @tracking_plans.each do |tracking_plan| %>
    <tr>
      <td><%= tracking_plan.id %></td>
      <td><%= tracking_plan.name %></td>


      <td><%= link_to 'Edit', edit_tracking_plan_path(tracking_plan) %></td> <td><%= link_to 'Show', tracking_plan_path(tracking_plan) %></td>
    </tr>
  <% end %>
  </tbody>
</table>

app/views/tracking_plans/new.html.erb
<div id="e-commerce-product" class="page-layout simple tabbed">

  <!-- HEADER -->
  <div class="page-header bg-primary text-auto row no-gutters align-items-center justify-content-between p-6">
    <div class="row no-gutters align-items-center" style="margin-left: 30px;padding: 10px;">
      <div style="font-size: 32px;font-weight: 700;">New Tracking Plan</div>
    </div>

    <button type="button" class="btn btn-light" onclick="submitForm()" style="margin-left:40px;">
      SAVE
    </button>

  </div>
  <!-- / HEADER -->

  <!-- CONTENT -->
  <%= render 'form', form_type: 'new' %>
  <!-- / CONTENT -->
</div>

app/views/tracking_plans/show.html.erb
<div style="font-size: 32px;font-weight: 700;margin: 10px 10px 20px 10px">
  Tracking Plan Details
</div>
<div style="margin:10px;font-size:18px">
  <div> <b>ID:</b> <%= @tracking_plan.id %></div>
  <div> <b>Name:</b> <%= @tracking_plan.name %></div>
  <div> <b>Events:</b>
  <% @tracking_plan.events.each do |event| %>
      <div><%= link_to event.name, event_path(event) %></div>
    <% end %>
</div>
</div>