config/routes.rb
Rails.application.routes.draw do

  get "/events", to: "events#index"

  resources :events
  resources :tracking_plans
  namespace :api do
    namespace :v1 do
      resources :events
      resources :tracking_plans
      post 'tracking_plans/add_events/:id' => 'tracking_plans#add_events'
      get 'tracking_plans/get_events/:id' => 'tracking_plans#get_events'
      post 'send_event' => 'send_event_api#send_event'
    end
    # post '/events/create_event' => 'events_api#create_event'
  end
end

app/models/event.rb
class Event < ApplicationRecord

  def self.create_event(params)
    name = params[:name]
    description = params[:description]
    rules = params[:rules]
    if name.blank? || description.blank? || rules.blank?
      return [false, 'Missing params', nil]
    end

    if self.name_exists(name)
      return [false, 'Event with this name already exists', nil]
    end

    event = Event.create(name: name, description: description, rules: rules)
    return [true, 'Event Created Successfully', event.id]
  end

  def self.update_event(params)
    id = params[:id]
    event = Event.find_by(id: id)
    return [false, 'Event doesn;t exist', event] if event.blank?

    if params[:name].present? && name_exists(params[:name])
      return [false, 'Event with this name already exists', event]
    end
    event.name = params[:name] if params[:name].present?
    event.description = params[:description] if params[:description].present?
    event.rules = params[:rules] if params[:rules].present?
    event = event.save
    return [true, 'Event updated Successfully', event]
  end

  def self.name_exists(name)
    Event.where(name: name).exists?
  end
end

app/controllers/api/v1/events_controller.rb
module Api
  module V1
    class EventsController < ApiController

      def create
        success, message, event_id = Event.create_event(params)
        unless success
          return response_data({}, message, 422, error: {})
        end
        response_data({event_id: event_id} , message, 200, error: {})
      end

      def index
        response_data(Event.all.as_json, 'All events!', 200, error: {})
      end

      def update
        success, message, event = Event.update_event(params)
        unless success
          return response_data({}, message, 422, error: {})
        end

        response_data(event.as_json, 'Updated event!', 200, error: {})
      end
    end
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update]
  def index
    @events = Event.all
  end

  def new
    @event = Event.new
  end

  def edit; end

  def create
    @event = Event.new
    event_params =  params[:event]
    event = {name: event_params[:name], description: event_params[:description], rules: event_params[:rules].as_json }
    success, message, event_id = Event.create_event(event)
    respond_to do |format|
      if success
        @event = Event.find(event_id)
        format.html { redirect_to events_path, notice: 'Event successfully created.' }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new }
        format.json { render json: message, status: :unprocessable_entity }
      end
    end
  end

  def show; end

  def update
    event_params =  params[:event]
    update_params = {}
    update_params[:id] = params[:id]
    update_params[:name] = event_params[:name]  if event_params[:name] != @event.name
    update_params[:description] = event_params[:description]  if event_params[:description] != @event.description
    update_params[:rules] = event_params[:rules]  if event_params[:rules] != @event.rules
    success, message, event = Event.update_event(update_params)
    respond_to do |format|
      if success
        @event = event
        format.html { redirect_to events_path, notice: 'Event successfully updated.' }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new }
        format.json { render json: message, status: :unprocessable_entity }
      end
    end
  end

  private

  def set_event
    @event = Event.find(params[:id])
  end

  def event_params
    params.require(:event).permit(:name, :description, :rules)
  end
end

app/helpers/api/v1/events_helper.rb
module Api::V1::EventsHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_form.html.erb
<div class="home-form-container" style="width: 90%; margin: auto;">
  <%= form_for @event, :html => {id: 'event_form', class: 'page-content'} do |f| %>
    <!--   Checking for error-->
    <% if @event.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@event.errors.count, "error") %> prohibited this page from being saved:</h2>
        <ul>
          <% @event.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="form-group">
      <%= f.label :name %><br>
      <%= f.text_field :name, class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= f.label :description %><br>
      <%= f.text_field :description, class: 'form-control' %>
    </div>


    <div class="form-group">
      <%= f.label :rules %><br>
      <%= f.text_area :rules, class: "form-textarea-input", cols: 100, rows: 10 %>
    </div>

<% end %>
</div>

<script type="text/javascript">
    function submitForm() {
        const form = document.getElementById('event_form');
        form.submit();
    }
</script>

app/views/events/edit.html.erb
<div class="page-layout simple tabbed">

  <!-- HEADER -->
  <div class="page-header bg-primary text-auto row no-gutters align-items-center justify-content-between p-6">
    <div class="row no-gutters align-items-center" style="margin-left: 30px;padding: 10px;">
     <div style="font-size: 32px;font-weight: 700;">Edit Event</div>
   </div>

  <button type="button" class="btn btn-light" onclick="submitForm()" style="margin-left:40px;">
    SAVE
  </button>

  </div>
  <!-- / HEADER -->

  <!-- CONTENT -->
  <%= render 'form', form_type: 'edit' %>
  <!-- / CONTENT -->
</div>

app/views/events/index.html.erb
<div style="margin:10px 10px; font-size: 48px; font-width: 700;">
  Events
</div>

<table class="table dataTable">

  <thead>
  <tr>
    <th>
      <div class="table-header">
        <span class="column-title">ID</span>
      </div>
    </th>

    <th>
      <div class="table-header">
        <span class="column-title">Name</span>
      </div>
    </th>
    <th>
      <div class="table-header">
        <span class="column-title">Description</span>
      </div>
    </th>

    <th>
      <div class="table-header">
        <span class="column-title">Actions</span>
      </div>
    </th>
  </tr>
  </thead>

  <tbody >
  <% @events.each do |event| %>
    <tr>
      <td><%= event.id %></td>
      <td><%= event.name %></td>
      <td><%= event.description %></td>
      <td><%= link_to 'Edit', edit_event_path(event) %></td> <td><%= link_to 'Show', event_path(event) %></td>
    </tr>
  <% end %>
  </tbody>
</table>

app/views/events/new.html.erb
<div id="e-commerce-product" class="page-layout simple tabbed" >

  <!-- HEADER -->
  <div class="page-header bg-primary text-auto row no-gutters align-items-center justify-content-between p-6">

    <div class="row no-gutters align-items-center" style="margin-left: 30px;padding: 10px;">
       <div style="font-size: 32px;font-weight: 700;">New Event</div>
    </div>

    <button type="button" class="btn btn-light" onclick="submitForm()" style="margin-left:40px;">
      SAVE
    </button>

  </div>
  <!-- / HEADER -->

  <!-- CONTENT -->
  <%= render 'form', form_type: 'new' %>
  <!-- / CONTENT -->
</div>

app/views/events/show.html.erb
<div style="font-size: 32px;font-weight: 700;margin: 10px 10px 20px 10px">
  Event Details
</div>
<div style="margin:10px;font-size:18px">
  <div> <b>ID:</b> <%= @event.id %></div>
  <div> <b>Name:</b> <%= @event.name %></div>
  <div> <b>Description:</b> <%= @event.description %></div>
  <div> <b>Rules:</b> <%= JSON.pretty_generate(@event.rules) %></div>
</div>